.TH OGMDEMUX "1" "November 2004" "ogmdemux v1.5" "User Commands"
.SH NAME
ogmdemux \- Extract streams from OGG/OGM files into separate files
.SH SYNOPSIS
.B ogmdemux
[\fIoptions\fR] \fIinname\fR
.SH DESCRIPTION
.LP
This program extracts all or only some streams from an OGM and
writes them to separate files.
.TP
\fIinname\fR
Use '\fIinname\fR' as the source.
.TP
\fB\-o\fR, \fB\-\-output\fR \fIout\fR
Use '\fIout\fR' as the base for destination file names.
\&'-v1', '-v2', '-a1', '-t1'... will be appended to
this name. Default: use '\fIinname\fR'.
.TP
\fB\-a\fR, \fB\-\-astream\fR \fIn\fR
Extract specified audio stream. Can be used more
than once. Default: extract all streams.
.TP
\fB\-d\fR, \fB\-\-vstream\fR \fIn\fR
Extract specified video stream. Can be used more
than once. Default: extract all streams.
.TP
\fB\-t\fR, \fB\-\-tstream\fR \fIn\fR
Extract specified text stream. Can be used more
than once. Default: extract all streams.
.TP
\fB\-na\fR, \fB\-\-noaudio\fR
Don't extract any audio streams.
.TP
\fB\-nv\fR, \fB\-\-novideo\fR
Don't extract any video streams.
.TP
\fB\-nt\fR, \fB\-\-notext\fR
Don't extract any text streams.
Default: extract all streams.
.TP
\fB\-r\fR, \fB\-\-raw\fR
Extract the raw streams only.
Default: extract to useful formats
(AVI, WAV, OGG, SRT...).
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Increase verbosity.
.TP
\fB\-h\fR, \fB\-\-help\fR
Show this help.
.TP
\fB\-V\fR,\fB \-\-version\fR
Show version number.
.SH NOTES
What works:
.TP
*
Extraction of the following formats is fully supported
including writing the stream contents to useful container formats:
.br
  video  -> AVI
.br
  Vorbis -> OGG/Vorbis
.br
  PCM    -> WAV
.br
  text   -> text files (SRT subtitle format)
.TP
*
All other audio streams (MP3, AC3) are just copied 1:1 into output
files. MP3 and AC3 files should be usable. Others might not.
.LP
What not works:
.TP
*
Headers created by older OggDS (DirectShow) filter
versions are not supported (and probably never will be).
.SH AUTHOR
.I ogmdemux
was written by Moritz Bunkus <moritz@bunkus.org>.
.SH SEE ALSO
.BR ogmmerge (1),
.BR ogmsplit (1),
.BR ogminfo (1),
.BR ogmcat (1),
.BR dvdxchap (1)
.SH WWW
The newest version can always be found at
.UR http://www.bunkus.org/videotools/ogmtools/
<http://www.bunkus.org/videotools/ogmtools/>
.UE
