.TH OGMINFO "1" "November 2004" "ogminfo v1.5" "User Commands"
.SH NAME
ogminfo \- Print information about streams in OGG/OGM files
.SH SYNOPSIS
.B ogminfo
[\fIoptions\fR] \fIinname\fR
.SH DESCRIPTION
.LP
This program lists all streams contained in an OGM including
information about the codecs used.
.TP
inname
Use '\fIinname\fR' as the source.
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Be verbose and show each OGG packet. See the section '\fBVERBOSITY LEVELS\fR'
for details.
.TP
\fB\-s\fR, \fB\-\-summary\fR
Will print a short summary for each stream including the total size in bytes,
the bitrate, the number of packets/frames and the length in seconds. This
requires the parsing of the complete file.
.TP
\fB\-h\fR, \fB\-\-help\fR
Show usage information.
.TP
\fB\-V\fR, \fB\-\-version\fR
Show version information.
.SH VERBOSITY LEVELS
.LP
The \fB-v\fR option can be used to increase \fBogminfo\fR's verbosity level
and print more information about the current file.
.TP
level 0
will print only the streams it finds and their types.
.TP
level 1
will also print each stream's header and comment packets' contents.
These two modes will not process the whole file (as opposed to all other
modes) if the comment packets are placed correctly.
.TP
level 2
will print a line for each OGG packet it encounters containing the stream
the packet belongs to, the payload size, the packet's granulepos, the
packet's number, its start time, its end time and several flags. The flags
may include 'sync_ok' or 'OUT_OF_SYNC' which indicates whether the
packet's placement in the file is correct according to its granulepos.
Other flags are 'IS_SYNCPOINT' or 'EOS'.
.br
level 2 and above automatically imply \fB\-\-summary\fR.
.TP
level 3
also prints a line whenever a new OGG page was read completely along with the
page's exact position in the file it was read from.
.TP
level 4
will dump the complete stream_header structure found in the header packet
for any non-Vorbis stream.
.LP
The levels 3 and 4 are intended for debugging purposes only.
.LP
.SH NOTES
What works:
.TP
*
OGM with Vorbis audio, 'normal' video (like DivX etc.), audio
streams (PCM, MP3 etc.), text streams (subtitles).
.LP
What not works:
.TP
*
Headers created by older OggDS (DirectShow) filter
versions are not supported (and probably never will be).
.SH AUTHOR
.I ogminfo
was written by Moritz Bunkus <moritz@bunkus.org>.
.SH SEE ALSO
.BR ogmmerge (1),
.BR ogmsplit (1),
.BR ogmdemux (1),
.BR ogmcat (1),
.BR dvdxchap (1)
.SH WWW
The newest version can always be found at
.UR http://www.bunkus.org/videotools/ogmtools/
<http://www.bunkus.org/videotools/ogmtools/>
.UE
