.TH OGMSPLIT "1" "November 2004" "ogmsplit v1.5" "User Commands"
.SH NAME
ogmsplit \- Split OGG/OGM files into sevaral smaller OGG/OGM files
.SH SYNOPSIS
.B ogmsplit
[\fIoptions\fR] \fIinname\fR
.SH DESCRIPTION
.LP
\fBogmsplit\fP can be used to easily split an OGM file after a given size.
Several OGM files will be created that each start with a keyframe.
.TP
inname
Use '\fIinname\fR' as the source.
.TP
\fB\-o\fR, \fB\-\-output\fR \fIout\fR
Use '\fIout\fR' as the base name. Ascending part numbers will be appended
to it. Default is '\fIinname\fR'. Examples:
.br
1) If \fB\-o\fR \fIoutput.ogg\fR is given on the command line then
\fBogmsplit\fR will create \fIoutput\-000001.ogg\fR, \fIoutput\-000002.ogg\fR
and so on.
.br
2) If no \fB\-o\fR option is given and the input's name is \fImovie.ogm\fR
then \fBogmsplit\fR will create \fImovie-000001.ogm\fR and so on.
.LP
The operation mode can be set with exactly one of \fB\-s\fR, \fB\-t,\fR
\fB\-c\fR or \fB\-p\fR. The default mode is to split by size (\fB\-s\fR).
.TP
\fB\-s\fR, \fB\-\-size\fR \fIsize\fR
Size in MiB ( = 1024 * 1024 bytes) after which a new
file will be opened (approximately). Default is 700MiB.
Size can end in 'B' to indicate 'bytes' instead of 'MiB'.
.TP
\fB\-t\fR, \fB\-\-time\fR \fItime\fR
Split after the given elapsed time (approximately).
\&'\fItime\fR' takes the form \fIHH:MM:SS.sss\fR or simply
\fISS\fR(.\fIsss\fR), e.g. 00:05:00.000 or 300.000 or simply 300.
.TP
\fB\-c\fR, \fB--cuts\fR \fIcuts\fR
Produce output files as specified by \fIcuts\fR, a list of
slices of the form "\fIstart\fR\-\fIend\fR" or "\fIstart\fR+\fIlength\fR",
separated by commas. If \fIstart\fR is omitted, it defaults
to the end of the previous cut. \fIstart\fR and \fIend\fR take
the same format as the arguments to \fB\-t\fR.
.TP
\fB\-n\fR, \fB\-\-num\fR \fInum\fR
Don't create more than \fInum\fR separate files. The last one
may be bigger than the desired size. Default is an unlimited number of files.
Can only be used with \fB-s\fR or \fB-t\fR.
.TP
\fB\-\-frontend\fR
Frontend mode. Progress output will be terminated by \\n instead of \\r.
.TP
\fB\-p\fR, \fB\-\-print-splitpoints\fR
Only print the key frames and the number of bytes encountered
before each. Useful to find the exact splitting point.
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Be verbose and show each OGG packet.
Can be used twice to increase verbosity.
.TP
\fB\-h\fR, \fB\-\-help\fR
Show this help.
.TP
\fB\-V\fR, \fB\-\-version\fR
Show version information.
.SH CHAPTER INFORMATION
\fBogmsplit\fR correctly handles chapter information. During the first
pass the chapter information, if any is present, will be adjusted to
match the output files generated. Chapters that are not contained in
the current output file are removed entirely. The other chapters
are renumbered to start at 1, and their timestamps will be recalculated.
.br
Example: If your source file contains these four chapters:
.LP
CHAPTER01=00:00:00.000
.br
CHAPTER01NAME=Chapter 01
.br
CHAPTER02=00:10:00.000
.br
CHAPTER02NAME=Chapter 02
.br
CHAPTER03=00:20:00.000
.br
CHAPTER03NAME=Chapter 03
.br
CHAPTER04=00:25:00.000
.br
CHAPTER04NAME=Chapter 04
.LP
and you split after 15 minutes, then the first output file will only
contain the first two chapters as shown above, and the second output
file will contain the following two chapters and the remaining part
of the first:
.LP
CHAPTER01=00:00:00.000
.br
CHAPTER01NAME=Chapter 02 (continued)
.br
CHAPTER02=00:05:00.000
.br
CHAPTER02NAME=Chapter 03
.br
CHAPTER03=00:10:00.000
.br
CHAPTER03NAME=Chapter 04
.LP
Note that only variable names are changed, not the chapter names themselves.
The exception is the first chapter of the second and following files where
"(continued)" is appended in order to indicate that this is not the start of
this chapter. If you want to change them as well you'll have to remerge the
resulting file with a new chapter file.
.SH AUTHOR
.I ogmsplit
was written by Moritz Bunkus <moritz@bunkus.org>.
.SH SEE ALSO
.BR ogmmerge (1),
.BR ogminfo (1),
.BR ogmdemux (1),
.BR ogmcat (1),
.BR dvdxchap (1)
.SH WWW
The newest version can always be found at
.UR http://www.bunkus.org/videotools/ogmtools/
<http://www.bunkus.org/videotools/ogmtools/>
.UE
